import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#5e5e5e",
        "tertiary-container": "#000000",
        "on-tertiary-fixed-variant": "#474747",
        "on-primary": "#303030",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary-fixed": "#e2e2e2",
        "primary-container": "#000000",
        "on-surface": "#e2e2e2",
        "on-secondary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#303030",
        "surface-container": "#1f1f1f",
        "on-primary-fixed": "#1b1b1b",
        "surface-container-low": "#1b1b1b",
        "on-tertiary": "#303030",
        tertiary: "#c6c6c6",
        "secondary-fixed": "#e2e2e2",
        "surface-variant": "#353535",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-container": "#757575",
        "on-secondary-container": "#b4b5b5",
        primary: "#c6c6c6",
        "on-tertiary-container": "#757575",
        "secondary-container": "#454747",
        "surface-dim": "#131313",
        "surface-container-highest": "#353535",
        surface: "#131313",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#393939",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#474747",
        "on-surface-variant": "#cfc4c5",
        outline: "#988e90",
        "primary-fixed-dim": "#c6c6c6",
        secondary: "#c6c6c7",
        "on-secondary": "#2f3131",
        "on-error": "#690005",
        "outline-variant": "#4c4546",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-background": "#e2e2e2",
        background: "#131313",
        "surface-tint": "#c6c6c6",
        "inverse-surface": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xl: "32px",
        "margin-mobile": "16px",
        md: "16px",
        sm: "12px",
        xs: "4px",
        lg: "24px",
        gutter: "16px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      keyframes: {
        rotate: { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "move-line": {
          "0%": { transform: "translateY(-100vh)", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { transform: "translateY(100vh)", opacity: "0" },
        },
        slide: { from: { transform: "translateY(0)" }, to: { transform: "translateY(-50%)" } },
        "fade-zoom-in": {
          from: { opacity: "0", transform: "translateY(2rem) scale(0.95)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)" },
        },
      },
      animation: {
        rotate: "rotate 20s linear infinite",
        "move-line": "move-line 8s linear infinite",
        slide: "slide 60s linear infinite",
        "fade-zoom-in": "fade-zoom-in 0.7s cubic-bezier(0.16,1,0.3,1) both",
      },
    },
  },
  future: { hoverOnlyWhenSupported: true },
  plugins: [],
};

export default config;
