spring:
  application:
    name: tripnode
  datasource:
    url: jdbc:mysql://localhost:3306/tripnode
    username: root
    password: Aman123@
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect